# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x0erecommendation\"*\n\x07Request\x12\x0e\n\x06\x64\x65part\x18\x01 \x01(\t\x12\x0f\n\x07\x61rrivee\x18\x02 \x01(\t\"@\n\x08Response\x12\x0c\n\x04prix\x18\x01 \x01(\t\x12\r\n\x05\x64uree\x18\x02 \x01(\t\x12\x17\n\x0fmoyen_transport\x18\x03 \x01(\t2U\n\x0bRecommender\x12\x46\n\x11GetRecommendation\x12\x17.recommendation.Request\x1a\x18.recommendation.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=33
  _globals['_REQUEST']._serialized_end=75
  _globals['_RESPONSE']._serialized_start=77
  _globals['_RESPONSE']._serialized_end=141
  _globals['_RECOMMENDER']._serialized_start=143
  _globals['_RECOMMENDER']._serialized_end=228
# @@protoc_insertion_point(module_scope)
